### ISSUE TITLE
Missing boiling_point and melting_point in fetch_table

### ISSUE THREAD

**Issue by eamsen** [lmmentel/mendeleev#177] opened 2024-09-29 01:40 UTC
## Describe the bug
Data returned via fetch_table does not contain the columns boiling_point and melting_point.

## To Reproduce
```
from mendeleev.fetch import fetch_table
elements = fetch_table("elements")
print(elements.info())
```

## Expected behavior
boiling_point and melting_point should be columns in the elements table.

## Specification

- 0.17.0, but older versions also seem affected
- python 3.9.12
- Ubuntu

**Comment by lmmentel** [comment] 2024-09-29 14:24
Thanks for reaching out. The issue is that `melting_point` and `boiling_point` are in a different table called `phasetransitions`. 

Your issue made me look into the docs and it seems that tables is missing from the [data access](https://mendeleev.readthedocs.io/en/latest/data_access.html) section of the docs. I'll create a separate issue to fix that. 

It seems that the python model `PhaseTransition` is also missing docs on the [api docs page](https://mendeleev.readthedocs.io/en/latest/api/mendeleev.models.html#module-mendeleev.models). 

To get the table with phase transitions you can simply reuse the logic you have 
 
```python
from mendeleev.fetch import fetch_table
pt = fetch_table("phasetransitions")
pt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   id                        108 non-null    int64  
 1   atomic_number             108 non-null    int64  
 2   boiling_point             91 non-null     float64
 3   melting_point             107 non-null    float64
 4   critical_temperature      34 non-null     float64
 5   critical_pressure         21 non-null     float64
 6   triple_point_temperature  17 non-null     float64
 7   triple_point_pressure     13 non-null     float64
 8   allotrope                 13 non-null     object 
dtypes: float64(6), int64(2), object(1)
memory usage: 7.7+ KB

``` 

An important caveat is that several elements have multiple allotropes with their separate values, e.g. for carbon:

```python
pt[pt.atomic_number == 6]
 
    id  atomic_number  boiling_point  melting_point  critical_temperature  critical_pressure  triple_point_temperature  triple_point_pressure allotrope
16  17              6        4098.15        4762.15                   NaN                NaN                   4762.15                10300.0  graphite
17  18              6            NaN        4713.15                   NaN                NaN                       NaN                    NaN   diamond
```

If you want to have all the data in one table you can join the `pt` dataframe with `elements`. You might want to decide first how you want to treat the allotropes first.

Here's all the atomic numbers where there is more than one allotrope:

```python
pt[pt['atomic_number'].duplicated()]['atomic_number'].unique()

array([ 6, 15, 34, 16, 50])
```

**Comment by lmmentel** [comment] 2024-09-29 14:33
FYI I recently added a method for exporting all tables from `mendeleev` [documented here](https://mendeleev.readthedocs.io/en/latest/data_access.html#export-data) but it requires executing commands in CLI.

**Comment by eamsen** [comment] 2024-09-29 20:31
Thank you for the swift response!
In that case, I was lead astray by the [documentation](https://mendeleev.readthedocs.io/en/stable/notebooks/bulk_data_access.html), but good to know that the data is actually available through a different table.

**Comment by lmmentel** [comment] 2024-09-29 20:54
The tutorial on data access seems a bit out of date. I've already updated some of the missing entries related to api docs and data but it seems I might have to look at the tutorials as well. I've made a separate issue #186 and therefore will close this one.

Feel free to reach out if you spot any other issues :)

**Closed by lmmentel** 2024-09-29 20:54 UTC
Labels: bug
