### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by AlanReviews** [lmmentel/mendeleev#25] opened 2020-11-08 14:17 UTC
## Describe the bug
I extracted an str element from a pandas dataframe. Then I saved it into a variable. I called the element function with the str element as a parameter. Then, I got the TypeError: 'str' object is not callable

## To Reproduce
1. from Mendeleev Import element
2. Extract a string data type from a table of elements and assign it to a variable
3. Call the element() function

## Expected behavior
I expect that the element function can process the string variable

## Specification

- mendleev 0.7.7
- python 3.8
- Windows 10

## Additional context
Here's my code:
```py
extractedElement = table3_df.iat[r,0]
print(type(extractedElement))
print(extractedElement)
tableElement = element(extractedElement) # The error is at this line
```

**Comment by lmmentel** [comment] 2020-11-08 14:35
Could you provide the outputs of the code snippet you attached? I would help to know the value of `extractedElement` you are passing to `element`.

**Comment by AlanReviews** [comment] 2020-11-08 14:38
Yes
```
<class 'str'>
aluminium
Traceback (most recent call last):
  File "c:\Users\Alan\Documents\VSCodeWorkspace\csv2xml\Simple-CSV-2-XML.py", line 101, in <module>
    tableElement = element(extractedElement)
TypeError: 'str' object is not callable
```

**Comment by lmmentel** [comment] 2020-11-08 14:49
Thanks, that makes it clearer. There seems to be two issues here:
1. It seems that the error you are seeing is caused by `element` variable being assigned a string somewhere between the import and the call you are making. Could you make sure that you are not reassigning the `element` variable anywhere.
2. passing lower case `aluminium` to `element` should raise an `NoResultFound: No row was found for one()` since the method works with capitalized names i.e. `element("Aluminum")` works. Notice that `mendeleev` uses the US spelling `Aluminum` instead of `Aluminium`. The safest way is probably to call the method with the symbol `"Al"` or the atomic number `13`.
Let me know if it worked.

**Comment by AlanReviews** [comment] 2020-11-08 15:04
Update: I believe the error is the second one. I was using Aluminium instead of Aluminum.

**Closed** 2020-11-10 22:13 UTC
Labels: bug

**Comment by AlanReviews** [comment] 2020-11-13 15:06
Is it possible to adapt Mendeleev to the Canadian spelling of elements?
